# This is a basic workflow to help you get started with Actions
name: Production Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: [ main ]
    paths-ignore:
      - "README.md"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install Dependencies (yarn)
        run: yarn
        env:
          FONT_AWESOME_TOKEN: ${{secrets.FONT_AWESOME_TOKEN}}
          SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
      - name: Build Site (webpack)
        run: yarn build
        env:
          FONT_AWESOME_TOKEN: ${{secrets.FONT_AWESOME_TOKEN}}
          SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
      - name: 🏗️ Setup Pages
        uses: actions/configure-pages@v1
      - name: 📦 Create and Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'dist/'
      - name: 🚀 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
